from __future__ import annotations
from pathlib import Path
from ..core.config import Config
from ..io.file_read import read_text_safe

SEPARATOR = "-" * 40


def render_transcript(
    project_name: str, tree_text: str, files: list[Path], config: Config
) -> str:
    header = (
        f"PROJECT TRANSCRIPT: {project_name}\n"
        f"Generated by ContextPacker\n"
        f"{'=' * 50}\n\n"
        f"Directory Tree:\n{tree_text}\n\n"
        f"{'=' * 50}\n\n"
    )

    body_parts: list[str] = []
    root = config.project_root

    for p in files:
        rel = p.relative_to(root)
        content = read_text_safe(p)
        entry = f"File: {rel}\n[\n{content}\n]\n{SEPARATOR}\n"
        body_parts.append(entry)

    return header + "".join(body_parts)
