from __future__ import annotations

PRESETS: dict[str, set[str]] = {
    "generic": set(),
    "rust": {
        "target",
        ".cargo",
        "*.rlib",
        "*.rmeta",
    },
    "csharp": {"bin", "obj", ".vs"},
    "node": {"node_modules", "dist", "build", ".next", ".git", "dist", "build", "package-lock.json", ".env", "public" },
    "python": {"__pycache__", ".venv", "venv", "*.pyc"},
    "android_kotlin": {
        ".gradle",
        ".idea",
        ".kotlin",
        "build",
        "captures",
        ".cxx",
        ".externalNativeBuild",
        "out",
    },
    "hc11cc": {"target", "__pycache__", ".venv", "venv", "EVBU"},
    "Android_Utility_Kernel": {
        "build",
        ".gradle",
        ".idea",
        ".kotlin",
        "captures",
        "local.properties",
        "*.iml",
        "*.apk",
        "*.aab",
        "*.ap_",
        "*.keystore",
        "*.jks",
        "*.hprof",
        "*.log",
        "gradle-wrapper.jar",
        "node_modules",
        "dist",
        ".vite",
        ".cache",
        "package-lock.json",
        "contextpacker_out",
    },
    "juce_cpp": {
        "build",
        ".cache",
        "cmake-build-*",
        "out",
        "bin",
        "obj",
        "*.o",
        "*.d",
        "*.ilk",
        "*.pdb",
        "*.pch",
        "*.suo",
        "*.user",
        "*.userosscache",
        "*.sln.docstates",
        "*.VC.db",
        "*.vspscc",
        "*.vssscc",
        "*.sw?"
    },
}
